### ISSUE TITLE
您好，我发现Tcpsession主动调用safeShutdown后，该session并没有被销毁

### ISSUE THREAD

**Issue by weibw-720** [ZLMediaKit/ZLToolKit#101]
流程大概是：
1.主动调用safeShutdown()
2.该session的onError()会被调用
此时正常情况该session就应该被销毁了，可是我发现他并没有销毁，仍在继续运行，onManager回调还在运行

不知是我哪里没搞懂，我比较初级

**Comment by xia-chu** [comment]
不会吧 这个不应该啊 你是不是改代码了？
