### ISSUE TITLE
 “stamp thread”是否可以删除？

### ISSUE THREAD

**Issue by louweijia** [ZLMediaKit/ZLToolKit#107]
测试发现 “stamp thread”【util.cpp中】占用单核1.7%，其主要操作时获取系统时间，并校验是否存在系统时间回退问题。
想请教一下，这个线程存在的意义，是否可以将这线程删除，有什么不可预测的问题？

**Comment by xia-chu** [comment]
1.7%的开销你这么在乎吗？

**Comment by xia-chu** [comment]
平常情况下 `stamp thread`没啥用；但是等负载上来了；就有大用了
