### ISSUE TITLE
ZLToolKit和mudo服务器的区别

### ISSUE THREAD

**Issue by zsxcandy** [ZLMediaKit/ZLToolKit#113]
你好，这个和陈硕写的mudo服务器有什么区别呢

**Comment by alexliyu7352** [comment]
自己不会看代码嘛?
差别有多大自己看readme能看到了.

就像你问spring与jfinal jboot 有什么区别呢?

zsxcandy ***@***.***> 于2022年6月23日周四 08:52写道：

**Comment by xia-chu** [comment]
我没仔细研究mudo代码 但是我觉得mudo言过其实了
