### ISSUE TITLE
请问下AsyncLogWriter出现corrupted size vs. prev_size异常导致signal SIGABRT，要怎么解决。

### ISSUE THREAD

**Issue by jiangjxuan** [ZLMediaKit/ZLToolKit#136]
@xia-chu 
老大，我使用ZLToolKit打印日志
以下初始化代码
```cpp
        auto channel = std::make_shared<ConsoleChannel>("ConsoleChn", (LogLevel)log_level);
        Logger::Instance().add(channel);
        Logger::Instance().setWriter(std::make_shared<AsyncLogWriter>());
```
程序启动后出现以下异常：
```text
corrupted size vs. prev_size
```
### 堆栈截图
![image](https://user-images.githubusercontent.com/24305958/205216826-5e77af5b-fd3f-421d-8031-9ea0f2b0fab5.png)

**Comment by xia-chu** [comment]
这个是打印了一条什么日志导致崩溃的 我觉得这个是次生崩溃问题 原始bug不在此处，请用valgrind调试你的程序

**Comment by jiangjxuan** [comment]
您好，请问下要怎么看打印什么内容出现异常？---- 回复的原邮件 ***@***.***>发送日期2022年12月02日 14:59 ***@***.***> ***@***.***>***@***.***>主题Re: [ZLMediaKit/ZLToolKit] 请问下AsyncLogWriter出现corrupted size vs. prev_size异常导致signal SIGABRT，要怎么解决。 (Issue #136)

这个是打印了一条什么日志导致崩溃的 我觉得这个是次生崩溃问题 原始bug不在此处，请用valgrind调试你的程序



—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

[

{

***@***.***": "http://schema.org",

***@***.***": "EmailMessage",

"potentialAction": {

***@***.***": "ViewAction",

"target": "https://github.com/ZLMediaKit/ZLToolKit/issues/136#issuecomment-1334834637",

"url": "https://github.com/ZLMediaKit/ZLToolKit/issues/136#issuecomment-1334834637",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

***@***.***": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]

**Comment by jiangjxuan** [comment]
解决了，请关闭

**Comment by xia-chu** [comment]
怎么解决的？定位到bug在什么位置？
