### ISSUE TITLE
poller线程的问题

### ISSUE THREAD

**Issue by sjd3211888** [zlmediakit/ZLToolKit#14]
比如我现在4核的机器，我启动的4个poller，但是我每次getpoller都是随机的，我如何能保证我一个数据只能在一个poller里面执行，如果是几个poller循环执行，会不会导致执行顺序不对导致数据不对的现象？

**Comment by xiongziliang** [comment]
目前EventPollerPool::getPoller方法的实现逻辑是这样的。
如果你执行该方法的线程就是EventPoller类型的线程，那么会返回当前的EventPoller对象。
如果不是EventPoller类型的线程，那么ZLToolKit会根据负载均衡算法，返回一条被认为低负载的
EventPoller对象给你。


所以如果你在非EventPoller线程中执行该方法，那么就会返回随机的poller对象给你。
开发者应该在对象生成时绑定一个唯一的Poller对象，这样就能避免多线程交织操作的问题。
