### ISSUE TITLE
使用 mini 解析不带节的ini文件，dump 时蹦了

### ISSUE THREAD

**Issue by lus-zzz** [ZLMediaKit/ZLToolKit#140]
![image](https://user-images.githubusercontent.com/33312081/212254454-2f475470-8334-43ff-8315-59ab33f32464.png)
 蹦在了第79行  
原因是使用tokenize 分割  `.BOOTPROTO` 字符串时返回的vector 大小为1

![image](https://user-images.githubusercontent.com/33312081/212254399-468dceda-bcc9-4c2e-a760-b8003e92eac8.png)

**Comment by xia-chu** [comment]
这个怎么关闭了？应该修复这个bug再关闭

**Comment by lus-zzz** [comment]
完全 不带节的 我想着不能算作 ini 文件 我看你例子里边  都是这样修改访问的
```c++
   ini["a"] = "true";
    ini["b"] = "false";
    ini["c"] = "123";
``` 

不带节的访问要加`.`
```c++
   ini[".a"] = "true";
    ini[".b"] = "false";
    ini[".c"] = "123";
``` 

dump不带节的时候 还会自动把key当作节名加上

**Comment by lus-zzz** [comment]
点错了

**Comment by xia-chu** [comment]
兼容了你提供的范例
