### ISSUE TITLE
在多个socket同时存在时，如何在收到一个socket client数据时，及时的将某些数据发送给另一个socket client

### ISSUE THREAD

**Issue by Shaw666** [ZLMediaKit/ZLToolKit#155]
您好，我没有很深入的理解，所以我目前使用onManager 来完成我题目提到的功能，当session A收到数据时，我全局保存该数据，并且在另一个session B OnManager触发时，将全局保存的数据发送给session B的client，但是这样操作session A和B之间的通信将有很大的延时，因为onManager是每2秒执行一次，当然我也不想提高onManager的执行频率，这肯定是个蠢办法，所以我想问问你有什么建议给我实现我的功能

**Comment by xia-chu** [comment]
调用 
otherSocket->getPoller()->async([](){
    otherSocket->send()....
});
