### ISSUE TITLE
遇到CPU过高的问题，用windbg找到可能是这个地方的问题

### ISSUE THREAD

**Issue by coolMre** [ZLMediaKit/ZLToolKit#161]
https://github.com/ZLMediaKit/ZLToolKit/blob/b6e5af3e7ad95d87f4e45a89e36d9a8ab45209a9/src/Poller/EventPoller.cpp#L229

这个地方有没有可能err一直不等于UV_EAGAIN,然后一直在这循环

00000021`7657aff8 00007ff9`ae369823 : 00000000`00000030 00000021`7657b1f8 00000021`7657b1f8 00000000`00000000 : ntdll!ZwDeviceIoControlFile+0xa
00000021`7657b000 00007ff9`b0cef857 : 00000000`00000120 00000021`7482d160 00007ff9`ae3696b0 00000021`7657b154 : mswsock!WSPRecv+0x2ef
00000021`7657b100 00007ff6`c8785493 : 00000000`fffff013 00000021`7657b210 00000000`00000400 00000100`00000000 : ws2_32!recv+0x197
00000021`7657b1a0 00007ff6`c874bfa7 : 00000000`fffff013 00000021`74855260 00007ff6`c929f710 00000021`76c66bf0 : MediaServer!toolkit::PipeWrap::read+0x33
00000021`7657b1d0 00007ff6`c874c570 : 00000021`74855290 00000021`747c9ee0 00000000`00000000 00007ff6`c929f710 : MediaServer!toolkit::EventPoller::onPipeEvent+0x47
00000021`7657b630 00007ff6`c874505c : 00000000`00000057 00000021`74838080 00000021`748385c0 00000021`748385c0 : MediaServer!toolkit::EventPoller::runLoop+0x3f0
00000021`7657f730 00007ff6`c8bed216 : 00000021`748385c0 00000021`748385c0 00000000`00000000 00000000`00000000 : MediaServer!std::thread::_Invoke<std::tuple<void (__cdecl toolkit::EventPoller::*)(bool,bool) __ptr64,toolkit::EventPoller * __ptr64,bool,bool>,0,1,2,3>+0x1c
00000021`7657f760 00007ff9`b13f13f2 : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 : MediaServer!thread_start<unsigned int (__cdecl*)(void *),1>+0x5a [minkernel\crts\ucrt\src\appcrt\startup\thread.cpp @ 97]
00000021`7657f790 00007ff9`b1a154f4 : 00007ff9`b13f13d0 00000000`00000000 00000000`00000000 00000000`00000000 : kernel32!BaseThreadInitThunk+0x22
00000021`7657f7c0 00000000`00000000 : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 : ntdll!RtlUserThreadStart+0x34

**Comment by xia-chu** [comment]
这个一般是是操作被打断了 才会进入重试 如果没数据 错误码就是EAGAIN。
这个代码是zltoolkit/zlmediakit的基石，如果有大问题，应该早就暴露并修复了。

**Comment by xia-chu** [comment]
不过这个可以改成EINTR, 类似libuv：
<img width="659" alt="图片" src="https://github.com/ZLMediaKit/ZLToolKit/assets/11495632/34f957f5-d755-4429-a5a3-f6ed35358ef4">

**Comment by xia-chu** [comment]
我看zltoolkit其他代码都是判断EINTR， 看来这个地方确实改下比较好：
<img width="950" alt="图片" src="https://github.com/ZLMediaKit/ZLToolKit/assets/11495632/0deb6219-541a-4703-962e-e68d5e03a82d">

**Comment by xia-chu** [comment]
@coolMre 来个pull request?

**Comment by xia-chu** [comment]
@baiyfcu 你之前遇到的Windows上cpu占用高的问题 会不会可能是这个原因？

**Comment by baiyfcu** [comment]
> @baiyfcu 你之前遇到的Windows上cpu占用高的问题 会不会可能是这个原因？

从CPU使用时长看，猜测是这个问题

**Comment by xia-chu** [comment]
这个问题应该已经修复了
