### ISSUE TITLE
无法获取peer_port, peer_ip 

### ISSUE THREAD

**Issue by swq123459** [ZLMediaKit/ZLToolKit#167]
dd1d308bd01a3aab038a87b938013be39134e1c1从这个commit开始(包括该commit), peer_port和peer_ip, 无法获取，这是在使用zlmediakit发现的，后来追踪到这个分支

**Comment by xia-chu** [comment]
udp还是tcp socket？

**Comment by xia-chu** [comment]
tcp并没发现这个问题：
<img width="1470" alt="图片" src="https://github.com/ZLMediaKit/ZLToolKit/assets/11495632/d98646b8-c8c2-4bc5-97fa-6010e8736e68">

**Comment by swq123459** [comment]
tcp

**Comment by xia-chu** [comment]
之前调用peer_port和peer_ip相关接口后 会把数据缓存下来 现在去掉这个逻辑。
因为先closeSocket操作放在onError之后了

**Comment by swq123459** [comment]
那就是预期行为吗

**Comment by xia-chu** [comment]
> 那就是预期行为吗

不是啊 触发onError以及Seession的析构函数时 都是可以获取到对端ip信息的
只要socket fd有效 都能获取到

**Comment by swq123459** [comment]
我这里可以必现，根据你的描述，我看能不能描述更清楚一些

**Comment by xia-chu** [comment]
这个是收到tcp reset时导致的 eof没这个问题，这个bug已经修复了 请查看最新代码

**Comment by xia-chu** [comment]
感谢反馈！
