### ISSUE TITLE
ios 16及以上，socket_ios 必现崩溃，急，麻烦大佬们帮忙看下。

### ISSUE THREAD

**Issue by dongdan002** [ZLMediaKit/ZLToolKit#176]
在ios上使用网络库，tcpsocket连接成功后，在ios层设置setSocketOfiOS时，必现崩溃
崩在了这一行：
BOOL r1 = CFReadStreamOpen((CFReadStreamRef)readStream);
setSocketOfiOS(int)
setConnected()

**Comment by xia-chu** [comment]
有崩溃堆栈不？具体哪句代码？截图看下

**Comment by dongdan002** [comment]
![image](https://github.com/ZLMediaKit/ZLToolKit/assets/19296952/81198ce9-835d-4503-b146-38834dc42ba9)

**Comment by dongdan002** [comment]
![image](https://github.com/ZLMediaKit/ZLToolKit/assets/19296952/e7fd4dec-8ad6-4e3f-8440-711a1b93a1f7)

**Comment by dongdan002** [comment]
> 

截图已经发了

**Comment by dongdan002** [comment]
> 

截图已经发了

**Comment by dongdan002** [comment]
> 有崩溃堆栈不？具体哪句代码？截图看下

setSocketOfIOS

**Comment by dongdan002** [comment]
> 有崩溃堆栈不？具体哪句代码？截图看下

setSocketOfIOS 和 unsetSocketOfIOS 这两个接口是必须的吗？我看其他文件里也没有用到 readStream和writeStream这两个对象。

**Comment by dongdan002** [comment]
注掉socket_ios.mm里的逻辑恢复正常，感谢夏工帮忙排查。
