### ISSUE TITLE
您好，请教下我将 libzltoolkit.a 和libzlmediakit.a 静态库加到项目中，编译后报错

### ISSUE THREAD

**Issue by qinlijie309** [ZLMediaKit/ZLToolKit#180]
/usr/bin/ld: /home/firefly/project/lib/libzltoolkit.a(SSLUtil.cpp.o): undefined reference to symbol 'TLS_server_method@@OPENSSL_1_1_0'
//usr/lib/aarch64-linux-gnu/libssl.so.1.1: error adding symbols: DSO missing from command line

编译静态库时候，将openssl打开了，编译静态库没有问题，但是放到项目中就报这个了

**Comment by xia-chu** [comment]
你项目还要链接libssl.so 和 libcrypto.so

**Comment by qinlijie309** [comment]
现在可以了，谢谢~
