### ISSUE TITLE
关于Socket::enableRecv在epoll 边沿模式下使用的bug

### ISSUE THREAD

**Issue by ss002012** [ZLMediaKit/ZLToolKit#237]
先说下使用场景：
我在用ZLToolKit实现一个tcp  proxy即创建一个中间tcp服务端，根据客户端请求的内容再把请求内容（作为一个中间tcp客户端）传递给真正的后端tcp服务，然后把后端tcp服务的返回数据传给请求客户端，tcp client----(server)tcp proxy(client)-----tcpserver。
有时后端tcpserver传递的速度很快，而客户端处理的很慢，所以直接调用send转发的话会导致内存暴增，我的处理是检测还有多少数据未发送给客户端，如果超过一定量则调用Socket::enableRecv(false)来停止对tcpserver的读监听，小于一定量再开启。但在使用中发现经过几次Socket::enableRecv(false)/Socket::enableRecv(true)的调用后，后面接受不到后端tcpserver的数据。

现在已经基本确定是epoll 边沿触发的问题了，因为首先禁用epoll改为select后就不存在这个问题；之后我尝试将用到的fd的触发模式改为水平模式触发，但发现在EventPoller::addEvent函数中水平模式不能和EPOLLEXCLUSIVE标识同时存在，否则可写一直触发无法关闭导致cpu占满，最后水平模式下把EPOLLEXCLUSIVE禁用掉才初步解决这个问题。
但上面的解决不优雅，且水平模式比边沿模式性能低，但边沿模式下我这边无法解决，请求大佬指导。

**Comment by xia-chu** [comment]
这个问题确实纯在 可以在开启接收时再手动触发下Socket::onRead

**Comment by ss002012** [comment]
多谢，我先试试大佬的方案。

**Comment by ss002012** [comment]
在我们云内环境上按照这个方案测试的确可行，但我们的代码是超过1年前的代码了，和最新代码实现有所不同；对应最新代码改动应该如下，但是我这边验证还需要一些点时间。
![image](https://github.com/user-attachments/assets/8b362130-5c45-4b4c-9e3b-677ea5a60cc1)

**Comment by xia-chu** [comment]
> 境上按照这个方案测试的确可行，但我们的代码是超过1年前的代码了，和最新代码实现有所不同；对应最新代码改动应该如下，但是我这边验证还需要一些点时间。

我觉得这样修改没问题 不过KQUEUE好像也是边缘触发

**Comment by ss002012** [comment]
有趣的现象。  
在[防止修改fd事件时报错](https://github.com/ZLMediaKit/ZLToolKit/commit/054f2f69e2c8f396a4ecdbc54a30a31de3cf2b97)commit之后的代码，不会存在我们说得开启读但读不会触发的问题。
在[防止修改fd事件时报错](https://github.com/ZLMediaKit/ZLToolKit/commit/054f2f69e2c8f396a4ecdbc54a30a31de3cf2b97)commit之前的代码，按照上面的修改方案测试epoll下是可用的(KQUEUE我没有条件测试)。
所以按照最新代码来说，不再需要额外的修改。  除非我们后面再把EPOLLEXCLUSIVE给加回来。

**Comment by ss002012** [comment]
> https://github.com/xia-chu/TcpProxy

谢谢提供的信息   我参考下。

**Comment by xia-chu** [comment]
> 改方案测试epoll下是可用的(KQUEUE我没有条件

那你这个修改我先不合入了

**Comment by ss002012** [comment]
> > 改方案测试epoll下是可用的(KQUEUE我没有条件
> 
> 那你这个修改我先不合入了

OK，现在不需要合入，测试没有问题。
