### ISSUE TITLE
Send函数多线程出现死锁问题

### ISSUE THREAD

**Issue by csenjoy** [ZLMediaKit/ZLToolKit#241]
ZLToolKit库版本：f8471ab1e6810358646f39e72f9ea035b1458363
Socket数据回调线程中，调用Send函数时，其他线程同时也调用了Send函数：如下图
![17223939688158](https://github.com/user-attachments/assets/a80b66bb-411d-4ced-9d07-fee9001d67f4)

**Comment by xia-chu** [comment]
所以要保证单线程访问Socket 请使用getPoller()获取对应线程，然后切换到这个poller线程去访问Socket函数的方法。
多路复用模式必须有一条驱动线程，这就意味着你的调用线程也得是这个驱动线程，如果是其他线程面临着线程安全的风险，用互斥锁也不是好办法。
