### ISSUE TITLE
test_pingpong 性能测试，千兆网卡带宽，带宽的80%下，为什么测试会频繁出现socket send timeout

### ISSUE THREAD

**Issue by muyiwq** [ZLMediaKit/ZLToolKit#243]
您好，测试最新的master分支，测试ZLToolKit目录下的test_pingpong.cpp，有些疑惑想请教一下.
在内网不同机器进行的测试：
tcpserver与tcpclient进行性能测试。
服务端运行test_pingpongServer -s 192.168.5.27:10000
默认10个tcp客户端 每个客户端100ms发送一次1MB的数据.10*10 =100MB/s
客户端运行test_pingpongClient -s 192.168.5.27     
在千兆网卡下，发送和接受速率100MB/s，属于正常的吗，但是在这种情况下，会出现socket send timeout，socket不可写的情况。

客户端运行test_pingpongClient -s 192.168.5.27  -c 1 -b 10000000 
1个客户端1s发送10次10MB数据，一样会出现，实测发现跟客户端数量,包大小，关系都不大。  
综合加起来的发送数据量80%接近或者大于带宽，大部分情况下会导致所有的socket都发送超时，有时候会随机剩余几个socket。这种情况都是正常的吗？
就算超过了带宽，为什么会导致所有socket都发送超时？，客户端就进行断开了。

如果我想传输2个大文件，比如都10GB，我用2个客户端，如何进行发送呢？既要保证带宽利用率，又要保证socket不发送超时断开？[
![Uploading 8b821c607a1ead726caec9df054e5a8.png…]()
](url)

**Comment by xia-chu** [comment]
socket send timeout一般表明带宽已经瓶颈了

**Comment by muyiwq** [comment]
现在的问题是接近带宽瓶颈，会导致所有的socket都发送超时，这种情况是合理的吗？最终导致带宽利用率为0%，而不是一直保持一个接近瓶颈的状态。 我想要的效果是就算接近带宽瓶颈或者超过，也是以接近带宽瓶颈的速率发送，其它无法发送超时我理解，为什么会导致所有的都超时呢？我能利用这个网络库实现这个效果吗？

**Comment by xia-chu** [comment]
当然合理了 tcp发送数据是不能丢的 是要可靠的 你在上游调用zltoolkit的接口 每秒产生的数据量是恒定的
但是带宽就这么多 你让zltoolkit怎么办？把你一部分的数据丢了？那这不是破坏了tcp可靠的前提吗？
发不出的数据怎么办？总不能让zltoolkit一直缓存到内存溢出？ 那zltoolkit只能掐断链接，直接不发了。

**Comment by xia-chu** [comment]
所以你要控制发送速度啊 要用onFlush回调控制啊。你看zlmediakit就用这个回调控制http文件下载速度，可以刚好达到网络最大发送速度。

**Comment by muyiwq** [comment]
多谢您抽空回答我的问题.
