### ISSUE TITLE
setReuseable sets whether the socket fd is written in reverse. 


### ISSUE THREAD

**Issue by ddwapple** [ZLMediaKit/ZLToolKit#244]
SO_REUSEPORT is set in `connect`.
```
int SockUtil::connect(const char *host, uint16_t port, bool async, const char *local_ip, uint16_t local_port) {
...
setReuseable(sockfd);
...
}
```

However, SO_REUSEPORT is unset in `listen`.
```
int SockUtil::listen(const uint16_t port, const char *local_ip, int back_log) {
...
setReuseable(fd, true, false);
...
}
```

I'm a little confused. Clients don't need to use SO_REUSEPORT, right? Only the server needs it. Thanks for the explanation. 

>在connect中会设置SO_REUSEPORT
```
int SockUtil::connect(const char *host, uint16_t port, bool async, const char *local_ip, uint16_t local_port) {
...
setReuseable(sockfd);
...
}
```

在listen中，却取消了SO_REUSEPORT设置
```
int SockUtil::listen(const uint16_t port, const char *local_ip, int back_log) {
...
setReuseable(fd, true, false);
...
}
```

有点不理解，客户端没必要使用SO_REUSEPORT吧，服务端才需要，谢谢解惑。

`TRANS_BY_GITHUB_AI_ASSISTANT`

**Comment by xia-chu** [comment]
先让我们看看函数怎么实现的，以及相关功能描述：
```c++
int SockUtil::setReuseable(int fd, bool on = true, bool reuse_port = true) {
    int opt = on ? 1 : 0;
    int ret = setsockopt(fd, SOL_SOCKET, SO_REUSEADDR, (char *) &opt, static_cast<socklen_t>(sizeof(opt)));
    if (ret == -1) {
        TraceL << "setsockopt SO_REUSEADDR failed";
        return ret;
    }
#if defined(SO_REUSEPORT)
    if (reuse_port) {
        ret = setsockopt(fd, SOL_SOCKET, SO_REUSEPORT, (char *) &opt, static_cast<socklen_t>(sizeof(opt)));
        if (ret == -1) {
            TraceL << "setsockopt SO_REUSEPORT failed";
        }
    }
#endif
    return ret;
}
```

- SO_REUSEADDR 主要用于使端口在套接字关闭后立即可用，或允许在某些情况下多个套接字绑定到同一个地址。
- SO_REUSEPORT 主要用于允许多个套接字在同一端口上并行监听，从而实现更好的负载均衡和性能。

**Comment by xia-chu** [comment]
这个修改是在 0e040d2b25dd2dd39ac0117560a3263bc4adb8f9 引入的，目的是解决端口被重复监听不报错的问题。

**Comment by xia-chu** [comment]
SO_REUSEPORT 应该默认都关闭，只有非常少见的情况下才应该开启。
目前也就udp server的情况下才存在多个Socket fd监听同一个Socket fd的需求

**Comment by ddwapple** [comment]
> SO_REUSEPORT should be turned off by default and should only be turned on in rare cases. Currently, there is only a need for multiple Socket fds to listen to the same port in the case of a UDP server.
> 
> > SO_REUSEPORT 应该默认都关闭，只有非常少见的情况下才应该开启。
> > 目前也就udp server的情况下才存在多个Socket fd监听同一个端口的需求
> 
> `TRANS_BY_GPT4`

嗯嗯，谢谢了，重新看了下代码，大概知道我的问题在哪。

**Comment by ddwapple** [comment]
> SO_REUSEPORT should be turned off by default and should only be turned on in rare cases. Currently, there is only a need for multiple Socket fds to listen to the same port in the case of a UDP server.
> 
> > SO_REUSEPORT 应该默认都关闭，只有非常少见的情况下才应该开启。
> > 目前也就udp server的情况下才存在多个Socket fd监听同一个端口的需求
> 
> `TRANS_BY_GPT4`

```
void TcpServer::start_l(uint16_t port, const std::string &host, uint32_t backlog) {
// 监听地址，产生fd，然后attachEvent(sock)，也就是放在对应epoller里面监听fd
if (!_socket->listen(port, host.c_str(), backlog)){}
for (auto &pr: _cloned_server) {
        // 启动子Server
       //  再次在各个子server里面监听fromSock_l(sock);->attachEvent(sock);
        pr.second->_socket->cloneSocket(*_socket);
}
}
```
看代码里面，主Server listren后，调用fromSock_l->attachEvent监听fd。
遍历子server，同时也都监听了listen后的fd，这样不会引起惊群效应嘛，服务端不设置SO_REUSEPORT，在EPOLL里面也没有使用EPOLLEXCLUSIVE标识，那有个链接过来，不会有问题吗，还是我看漏了，谢谢指导。

**Comment by xia-chu** [comment]
开启EPOLLEXCLUSIVE后又有其他问题，比如说修改事件会失败，所以去掉EPOLLEXCLUSIVE标记了。
你可以参考下： https://github.com/ZLMediaKit/ZLToolKit/issues/226

**Comment by ddwapple** [comment]
> After enabling EPOLLEXCLUSIVE, there are other problems, such as modifying events will fail, so the EPOLLEXCLUSIVE flag is removed. You can refer to: #226
> 
> > 开启EPOLLEXCLUSIVE后又有其他问题，比如说修改事件会失败，所以去掉EPOLLEXCLUSIVE标记了。
> > 你可以参考下： #226
> 
> `TRANS_BY_GITHUB_AI_ASSISTANT`

嗯嗯，谢谢。
