### ISSUE TITLE
if ZLToolKit supports add custom data in connection

### ISSUE THREAD

**Issue by Angel-dawn** [ZLMediaKit/ZLToolKit#255]
a scene:
   i want to use state in connection to deal data

**Comment by Angel-dawn** [comment]
a scene : use TcpServer and TcpClient handshake i want to use state to dispatch different rule if zltoolkit support add custom data in connection

**Comment by xia-chu** [comment]
Sorry, I didn't understand what you meant. Could you provide some example code?

**Comment by Angel-dawn** [comment]
> Sorry, I didn't understand what you meant. Could you provide some example code?
`int main(int argc,const char ** agrv)
{
    eventloop_thread.Run();
    EventLoop *loop = eventloop_thread.Loop();

    if(loop)
    {
        InetAddress server("192.168.1.200:1935");
        std::shared_ptr<TcpClient> client = std::make_shared<TcpClient>(loop,server);
        client->SetRecvMsgCallback([](const TcpConnectionPtr&con,MsgBuffer &buf){
            RtmpHandShakePtr shake = con->GetContext<RtmpHandShake>(kNormalContext);
            shake->HandShake(buf);
        });
        client->SetCloseCallback([](const TcpConnectionPtr &con){
            if(con)
            {
                std::cout << "host:" << con->PeerAddr().ToIpPort() << " closed." << std::endl;
            }
        });
        client->SetWriteCompleteCallback([](const TcpConnectionPtr &con){
            if(con)
            {
                std::cout << "host:" << con->PeerAddr().ToIpPort() << " write complete. " << std::endl;
                RtmpHandShakePtr shake = con->GetContext<RtmpHandShake>(kNormalContext);
                shake->WriteComplete();
            }
        });
        client->SetConnectCallback([](const TcpConnectionPtr&con,bool connected){
            if(connected)
            {
                RtmpHandShakePtr shake = std::make_shared<RtmpHandShake>(con,true);
                con->SetContext(kNormalContext,shake);
                shake->Start();
                
            }
        });
        client->Connect();
        while(1)
        {
            std::this_thread::sleep_for(std::chrono::seconds(1));
        }
    }    
    return 0;
}`

`int main(int argc,const char ** agrv)
{
    eventloop_thread.Run();
    EventLoop *loop = eventloop_thread.Loop();

    if(loop)
    {
        InetAddress listen("192.168.1.200:1935");
        TcpServer server(loop,listen);
        server.SetMessageCallback([](const TcpConnectionPtr&con,MsgBuffer &buf){
            RtmpHandShakePtr shake = con->GetContext<RtmpHandShake>(kNormalContext);
            shake->HandShake(buf);
        });
        server.SetNewConnectionCallback([&loop](const TcpConnectionPtr &con){
                RtmpHandShakePtr shake = std::make_shared<RtmpHandShake>(con,false);
                con->SetContext(kNormalContext,shake);
                shake->Start();
                con->SetWriteCompleteCallback([&loop](const TcpConnectionPtr&con){
                std::cout << "write complete host:" << con->PeerAddr().ToIpPort() << std::endl;
                RtmpHandShakePtr shake = con->GetContext<RtmpHandShake>(kNormalContext);
                shake->WriteComplete();
            });
        });
        server.Start();
        while(1)
        {
            std::this_thread::sleep_for(std::chrono::seconds(1));
        }
    }    
    return 0;
}`

**Comment by Angel-dawn** [comment]
> Sorry, I didn't understand what you meant. Could you provide some example code?
ok like this code i parse  rtmp handshake
 if server receive Message i will use
TcpServer server(loop,listen);
        server.SetMessageCallback([](const TcpConnectionPtr&con,MsgBuffer &buf){
            RtmpHandShakePtr shake = con->GetContext<RtmpHandShake>(kNormalContext);
            shake->HandShake(buf);
        });
        server.SetNewConnectionCallback([&loop](const TcpConnectionPtr &con){
                RtmpHandShakePtr shake = std::make_shared<RtmpHandShake>(con,false);
                con->SetContext(kNormalContext,shake);
                shake->Start();
                con->SetWriteCompleteCallback([&loop](const TcpConnectionPtr&con){
                std::cout << "write complete host:" << con->PeerAddr().ToIpPort() << std::endl;
                RtmpHandShakePtr shake = con->GetContext<RtmpHandShake>(kNormalContext);
                shake->WriteComplete();
            });
        });
        server.Start();

in client peer 
client->SetRecvMsgCallback([](const TcpConnectionPtr&con,MsgBuffer &buf){
            RtmpHandShakePtr shake = con->GetContext<RtmpHandShake>(kNormalContext);
            shake->HandShake(buf);
        });
client->SetWriteCompleteCallback([](const TcpConnectionPtr &con){
            if(con)
            {
                std::cout << "host:" << con->PeerAddr().ToIpPort() << " write complete. " << std::endl;
                RtmpHandShakePtr shake = con->GetContext<RtmpHandShake>(kNormalContext);
                shake->WriteComplete();
            }
        });
        client->SetConnectCallback([](const TcpConnectionPtr&con,bool connected){
            if(connected)
            {
                RtmpHandShakePtr shake = std::make_shared<RtmpHandShake>(con,true);
                con->SetContext(kNormalContext,shake);
                shake->Start();
                
            }
        });
        client->Connect();

**Comment by Angel-dawn** [comment]
> Sorry, I didn't understand what you meant. Could you provide some example code?
TcpServer server(loop,listen);
        server.SetMessageCallback([](const TcpConnectionPtr&con,MsgBuffer &buf){
            RtmpHandShakePtr shake = con->GetContext<RtmpHandShake>(kNormalContext);
            shake->HandShake(buf);
        });
        server.SetNewConnectionCallback([&loop](const TcpConnectionPtr &con){
                RtmpHandShakePtr shake = std::make_shared<RtmpHandShake>(con,false);
                con->SetContext(kNormalContext,shake);
                shake->Start();
                con->SetWriteCompleteCallback([&loop](const TcpConnectionPtr&con){
                std::cout << "write complete host:" << con->PeerAddr().ToIpPort() << std::endl;
                RtmpHandShakePtr shake = con->GetContext<RtmpHandShake>(kNormalContext);
                shake->WriteComplete();
            });
        });
        server.Start();

**Comment by Angel-dawn** [comment]
> > Sorry, I didn't understand what you meant. Could you provide some example code?
 TcpServer server(loop,listen);
 server.SetMessageCallback([](const TcpConnectionPtr&con,MsgBuffer &buf){
 RtmpHandShakePtr shake = con->GetContext(kNormalContext);
 shake->HandShake(buf);
 });
 server.SetNewConnectionCallback([&loop](const TcpConnectionPtr &con){
 RtmpHandShakePtr shake = std::make_shared(con,false);
 con->SetContext(kNormalContext,shake);
> > shake->Start();
> > con->SetWriteCompleteCallback([&loop](const TcpConnectionPtr&con){
> > std::cout << "write complete host:" << con->PeerAddr().ToIpPort() << std::endl;
> > RtmpHandShakePtr shake = con->GetContext(kNormalContext);
> > shake->WriteComplete();
> > });
> > });
> > server.Start();


client->SetRecvMsgCallback([](const TcpConnectionPtr&con,MsgBuffer &buf){
            RtmpHandShakePtr shake = con->GetContext<RtmpHandShake>(kNormalContext);
            shake->HandShake(buf);
        });
        client->SetCloseCallback([](const TcpConnectionPtr &con){
            if(con)
            {
                std::cout << "host:" << con->PeerAddr().ToIpPort() << " closed." << std::endl;
            }
        });
        client->SetWriteCompleteCallback([](const TcpConnectionPtr &con){
            if(con)
            {
                std::cout << "host:" << con->PeerAddr().ToIpPort() << " write complete. " << std::endl;
                RtmpHandShakePtr shake = con->GetContext<RtmpHandShake>(kNormalContext);
                shake->WriteComplete();
            }
        });
        client->SetConnectCallback([](const TcpConnectionPtr&con,bool connected){
            if(connected)
            {
                RtmpHandShakePtr shake = std::make_shared<RtmpHandShake>(con,true);
                con->SetContext(kNormalContext,shake);
                shake->Start();
                
            }
        });
        client->Connect();

**Comment by Angel-dawn** [comment]
> Sorry, I didn't understand what you meant. Could you provide some example code?
> TcpServer server(loop,listen);
        server.SetMessageCallback([](const TcpConnectionPtr&con,MsgBuffer &buf){
            RtmpHandShakePtr shake = con->GetContext<RtmpHandShake>(kNormalContext);
            shake->HandShake(buf);
        });
        server.SetNewConnectionCallback([&loop](const TcpConnectionPtr &con){
                RtmpHandShakePtr shake = std::make_shared<RtmpHandShake>(con,false);
                con->SetContext(kNormalContext,shake);
                shake->Start();
                con->SetWriteCompleteCallback([&loop](const TcpConnectionPtr&con){
                std::cout << "write complete host:" << con->PeerAddr().ToIpPort() << std::endl;
                RtmpHandShakePtr shake = con->GetContext<RtmpHandShake>(kNormalContext);
                shake->WriteComplete();
            });
        });
        server.Start();

**Comment by Angel-dawn** [comment]
> Sorry, I didn't understand what you meant. Could you provide some example code?
InetAddress server("192.168.1.200:1935");
        std::shared_ptr<TcpClient> client = std::make_shared<TcpClient>(loop,server);
        client->SetRecvMsgCallback([](const TcpConnectionPtr&con,MsgBuffer &buf){
            RtmpHandShakePtr shake = con->GetContext<RtmpHandShake>(kNormalContext);
            shake->HandShake(buf);
        });
        client->SetCloseCallback([](const TcpConnectionPtr &con){
            if(con)
            {
                std::cout << "host:" << con->PeerAddr().ToIpPort() << " closed." << std::endl;
            }
        });
        client->SetWriteCompleteCallback([](const TcpConnectionPtr &con){
            if(con)
            {
                std::cout << "host:" << con->PeerAddr().ToIpPort() << " write complete. " << std::endl;
                RtmpHandShakePtr shake = con->GetContext<RtmpHandShake>(kNormalContext);
                shake->WriteComplete();
            }
        });
        client->SetConnectCallback([](const TcpConnectionPtr&con,bool connected){
            if(connected)
            {
                RtmpHandShakePtr shake = std::make_shared<RtmpHandShake>(con,true);
                con->SetContext(kNormalContext,shake);
                shake->Start();
                
            }
        });
        client->Connect();

**Comment by Angel-dawn** [comment]
i am parsing rtmp protocol when new connection connect server i want to set  a context in connection and when server receive message i want to use the context which i set to connection to execete handshake

**Comment by xia-chu** [comment]
@Angel-dawn 
Hi, you can use `Socket` like this:
```
auto sock = Socket::createSocket(poller);

// SetRecvMsgCallback
sock->setOnRead([] (Buffer::Ptr &buf, struct sockaddr *addr, int addr_len) {});

// SetCloseCallback
sock->setOnErr([] (const SockException &err) {});

// SetWriteCompleteCallback
sock->setOnFlush([] () -> bool {});

// connect and SetConnectCallback
sock->connect("192.168.1.200", 1935, [] (const SockException &err) {
});
```

**Comment by Angel-dawn** [comment]
client->SetWriteCompleteCallback([](const TcpConnectionPtr &con){
            if(con)
            {
                std::cout << "host:" << con->PeerAddr().ToIpPort() << " write complete. " << std::endl;
                RtmpHandShakePtr shake = con->GetContext<RtmpHandShake>(kNormalContext);
                shake->WriteComplete();
            }
        });
        client->SetConnectCallback([](const TcpConnectionPtr&con,bool connected){
            if(connected)
            {
                RtmpHandShakePtr shake = std::make_shared<RtmpHandShake>(con,true);
                con->SetContext(kNormalContext,shake);
                shake->Start();
                
            }
        });
i want set RtmpHandShake to connection and the RtmpHandShake will  send c0c1 s0s1 data finish handshake or can you give me some code that how you implement the parse rtmp

**Comment by xia-chu** [comment]
@Angel-dawn You can use [zlmediakit](https://github.com/ZLMediaKit/ZLMediaKit)
