### ISSUE TITLE
多进程支持不？

### ISSUE THREAD

**Issue by CangJieStore** [ZLMediaKit/ZLToolKit#42]

**Comment by xia-chu** [comment]
为什么要多进程？



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: CangJieStore <notifications@github.com&gt;
发送时间: 2020年11月24日 21:51
收件人: xia-chu/ZLToolKit <ZLToolKit@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[xia-chu/ZLToolKit] 多进程支持不？ (#42)

**Comment by CangJieStore** [comment]
一个parent process，n个child process，在不考虑ipc的情况下，用这个框架通信

**Comment by xia-chu** [comment]
zlm是多线程的 所以不需要多进程



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: CangJieStore <notifications@github.com&gt;
发送时间: 2020年11月25日 17:38
收件人: xia-chu/ZLToolKit <ZLToolKit@noreply.github.com&gt;
抄送: 夏楚 <771730766@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[xia-chu/ZLToolKit] 多进程支持不？ (#42)





 
一个parent process，n个child process，在不考虑ipc的情况下，用这个框架通信
