### ISSUE TITLE
楼主，貌似少了发送超时的处理

### ISSUE THREAD

**Issue by CangJieStore** [ZLMediaKit/ZLToolKit#43]

**Comment by xia-chu** [comment]
什么超时？



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: CangJieStore <notifications@github.com&gt;
发送时间: 2020年11月30日 10:12
收件人: xia-chu/ZLToolKit <ZLToolKit@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[xia-chu/ZLToolKit] 楼主，貌似少了发送超时的处理 (#43)

**Comment by xia-chu** [comment]
发送超时会断开连接的



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: CangJieStore <notifications@github.com&gt;
发送时间: 2020年11月30日 10:12
收件人: xia-chu/ZLToolKit <ZLToolKit@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[xia-chu/ZLToolKit] 楼主，貌似少了发送超时的处理 (#43)
