### ISSUE TITLE
SqlPool 不能异步查询吗？

### ISSUE THREAD

**Issue by bobz202** [ZLMediaKit/ZLToolKit#48]
SqlPool 不能异步查询吗？

**Comment by xia-chu** [comment]
不能 因为mysqlclient的sdk就是同步的



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: bobz202 <notifications@github.com&gt;
发送时间: 2021年1月7日 18:03
收件人: xia-chu/ZLToolKit <ZLToolKit@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[xia-chu/ZLToolKit] SqlPool 不能异步查询吗？ (#48)





 
SqlPool 不能异步查询吗？
