### ISSUE TITLE
error C2872: “byte”: 不明确的符号

### ISSUE THREAD

**Issue by brinkqiang** [ZLMediaKit/ZLToolKit#49]
1>util.cpp
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\shared\rpcndr.h(192,14): error C2872: “byte”: 不明确的符号
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\shared\rpcndr.h(191,23): message : 可能是“unsigned char byte”
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.28.29333\include\cstddef(29,12): message : 或    “std::byte”
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\shared\rpcndr.h(962,25): error C2872: “byte”: 不明确的符号
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\shared\rpcndr.h(191,23): message : 可能是“unsigned char byte”

**Comment by brinkqiang** [comment]
vs2019/WIN10

**Comment by brinkqiang** [comment]
与编译选项 ADD_COMPILE_OPTIONS("/std:c++latest") 冲突

**Comment by wasphin** [comment]
长时间没有更新, 也比较久远了, 先关闭了.
