### ISSUE TITLE
能添加下定时器吗？

### ISSUE THREAD

**Issue by iahob** [ZLMediaKit/ZLToolKit#53]
能用c++11 封装下timewheel 吗？

**Comment by xia-chu** [comment]
现在最小堆 不能满足你的需求吗？你的定时器是海量的吗



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Yw ***@***.***&gt;
发送时间: 2021年3月18日 19:05
收件人: xia-chu/ZLToolKit ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: 回复：[xia-chu/ZLToolKit] 能添加下定时器吗？ (#53)





 
能用c++11 封装下timewheel 吗？

**Comment by HangZhouCoder** [comment]
目前skynet封装了时间轮c库，c++11 实现的没有特别出名的，想看看大佬们能不能实现一个完善的

**Comment by ktprime** [comment]
@iahob 试试我实现的， https://github.com/ktprime/ktprime/blob/master/wheel_timer.cpp
时间轮的问题是取小触发时间不是O(1)
