### ISSUE TITLE
编译报错

### ISSUE THREAD

**Issue by tonyonce2017** [ZLMediaKit/ZLToolKit#57]
![image](https://user-images.githubusercontent.com/34465929/120574355-be5b9480-c451-11eb-9cce-7d22705590dc.png)
编译示例的时候会报错, 可以不编译示例吗?
arm架构

**Comment by tonyonce2017** [comment]
操作系统是: raspberryPi

**Comment by tonyonce2017** [comment]
GCC 8.3

**Comment by tonyonce2017** [comment]
嗯..按照网上教程 在CMakeLists.txt 里加 set(CMAKE_CXX_LINK_FLAGS "${CMAKE_CXX_LINK_FLAGS} -latomic") 解决了

**Comment by xia-chu** [comment]
那就好
