### ISSUE TITLE
# 代码请教

### ISSUE THREAD

**Issue by Mr-zhang-97** [ZLMediaKit/ZLToolKit#60]
![图片](https://user-images.githubusercontent.com/53998171/121110913-9cdb1e00-c840-11eb-93b4-7fc38a9c4383.png)
logger里的函数Instance（）没有定义，为什么可以直接使用呢？有大佬可以提点一二吗。

**Comment by xia-chu** [comment]
有定意的 用宏定义的





发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Mr-zhang-97 ***@***.***&gt;
发送时间: 2021年6月8日 10:07
收件人: ZLMediaKit/ZLToolKit ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: 回复：[ZLMediaKit/ZLToolKit] # 代码请教 (#60)
