### ISSUE TITLE
undefined reference to `__atomic_load_8' 

### ISSUE THREAD

**Issue by lyfpeter** [ZLMediaKit/ZLToolKit#61]
遇到上述问题，需要加set(CMAKE_CXX_LINK_FLAGS "${CMAKE_CXX_LINK_FLAGS} -latomic")

**Comment by xia-chu** [comment]
嗯 你是交叉编译吧?交叉编译环境 可能libstdc++库默认不带atomic组件 应该主要为了节省内存
