### ISSUE TITLE
写日志的线程同步问题

### ISSUE THREAD

**Issue by wujianGit123** [ZLMediaKit/ZLToolKit#62]
写日志经常会在不同的线程同时进行，因为在写日志的时候会创建新日志文件和删除旧日志文件，当线程1在创建新日志文件的时候，而线程2同时删除旧日志文件，程序就会崩溃，建议作者修改此bug

**Comment by xia-chu** [comment]
请使用    `Logger::Instance().setWriter(std::make_shared<AsyncLogWriter>())`;来确保线程安全，否则不是线程安全的。

**Comment by wujianGit123** [comment]
> 请使用 `Logger::Instance().setWriter(std::make_shared<AsyncLogWriter>())`;来确保线程安全，否则不是线程安全的。

好的，多谢！
