### ISSUE TITLE
历史日志文件清除失败

### ISSUE THREAD

**Issue by ChnPhantom** [ZLMediaKit/ZLToolKit#64]
如果程序一直运行，并只设置了一天保留，在第二天时并不会删除第一天产生的文件，这是我临时修改的代码
![image](https://user-images.githubusercontent.com/5669600/127268907-88f60982-fa2a-4947-9705-f55f8940f857.png)

**Comment by xia-chu** [comment]
会删除吧？我都是设置7天左右 ，能验证确实没7天前的日志文件了，保留一天日志我没验证，应该也能删除啊。

**Comment by xia-chu** [comment]
还有 重启程序，不会去删除2天前的日志的。程序只会删除本次运行时产生的老文件

**Comment by ChnPhantom** [comment]
明白了，可能是我们理解有误
