### ISSUE TITLE
您好 socket能否添加对重连机制的支持

### ISSUE THREAD

**Issue by coding-lxm** [ZLMediaKit/ZLToolKit#66]
博主，项目中用到的tcp socket经常需要用到重连机制，能否在socket中添加个可配置的重连机制

**Comment by xia-chu** [comment]
为了支持上次五花八门的业务和功能，底层api肯定是细粒度的，你说的重连场景只是一种业务而已，而且什么错误时重连？重连间隙是多少？重连多少次？这些都是很业务的事情，应该在上层代码去实现的。而且我都把onErr(断开)事件抛出来了，自己实现下重连多难呢？ zlmediakit有很多重连这样的场景啊，并不一定要在zltoolkit实现啊

**Comment by coding-lxm** [comment]
好的  感谢回复
