### ISSUE TITLE
安卓编译报错

### ISSUE THREAD

**Issue by dengly** [ZLMediaKit/ZLToolKit#68]
- ndk 是 android-ndk-r14b
- 系统是 macOS Big Sur 11.5.2

在 ZLToolKit 目录下直接运行 build_for_android.sh，报以下错误

```
ZLToolKit/src/Network/Session.cpp: In member function 'virtual std::string toolkit::Session::getIdentifier() const':
ZLToolKit/src/Network/Session.cpp:21:12: error: 'to_string' is not a member of 'std'
     return std::to_string(reinterpret_cast<uint64_t>(this));
            ^
ZLToolKit/src/Network/Session.cpp:21:12: note: suggested alternative:
In file included from ZLToolKit/src/Network/Socket.h:22:0,
                 from ZLToolKit/src/Network/Session.h:16,
                 from ZLToolKit/src/Network/Session.cpp:11:
ZLToolKit/src/Util/util.h:209:13: note:   'toolkit::to_string'
 std::string to_string(T value){
             ^
At global scope:
cc1plus: warning: unrecognized command line option "-Wno-predefined-identifier-outside-function"
make[2]: *** [CMakeFiles/ZLToolKit_static.dir/src/Network/Session.cpp.o] Error 1
make[1]: *** [CMakeFiles/ZLToolKit_static.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by xia-chu** [comment]
修复了 更新下ZLToolKit

**Comment by dengly** [comment]
同步更新代码后，编译依然有报错，但错误信息不一样了。

```
ZLToolKit/tests/test_threadPoolBenchmark.cpp: In lambda function:
ZLToolKit/tests/test_threadPoolBenchmark.cpp:23:15: error: 'exit' was not declared in this scope
         exit(0);
               ^
At global scope:
cc1plus: warning: unrecognized command line option "-Wno-predefined-identifier-outside-function"
make[2]: *** [tests/CMakeFiles/test_threadPoolBenchmark.dir/test_threadPoolBenchmark.cpp.o] Error 1
make[1]: *** [tests/CMakeFiles/test_threadPoolBenchmark.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
../lib/libZLToolKit.a(logger.cpp.o):logger.cpp:function toolkit::ConsoleChannel::write(toolkit::Logger const&, std::shared_ptr<toolkit::LogContext> const&): error: undefined reference to '__android_log_print'
../lib/libZLToolKit.a(logger.cpp.o):logger.cpp:function toolkit::ConsoleChannel::write(toolkit::Logger const&, std::shared_ptr<toolkit::LogContext> const&): error: undefined reference to '__android_log_print'
collect2: error: ld returned 1 exit status
collect2: error: ld returned 1 exit status
make[2]: *** [bin/test_udpSock] Error 1
make[2]: *** [bin/test_timer] Error 1
make[1]: *** [tests/CMakeFiles/test_udpSock.dir/all] Error 2
make[1]: *** [tests/CMakeFiles/test_timer.dir/all] Error 2
../lib/libZLToolKit.a(logger.cpp.o):logger.cpp:function toolkit::ConsoleChannel::write(toolkit::Logger const&, std::shared_ptr<toolkit::LogContext> const&): error: undefined reference to '__android_log_print'
collect2: error: ld returned 1 exit status
make[2]: *** [bin/test_tcpClient] Error 1
make[1]: *** [tests/CMakeFiles/test_tcpClient.dir/all] Error 2
make: *** [all] Error 2
../lib/libZLToolKit.a(logger.cpp.o):logger.cpp:function toolkit::ConsoleChannel::write(toolkit::Logger const&, std::shared_ptr<toolkit::LogContext> const&): error: undefined reference to '__android_log_print'
collect2: error: ld returned 1 exit status
make[2]: *** [bin/test_udpSock] Error 1
make[1]: *** [tests/CMakeFiles/test_udpSock.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by xia-chu** [comment]
你直接用android studio编译吧 我昨晚编译过了



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 邓燎燕 ***@***.***&gt;
发送时间: 2021年9月11日 14:41
收件人: ZLMediaKit/ZLToolKit ***@***.***&gt;
抄送: 夏楚 ***@***.***&gt;, State change ***@***.***&gt;
主题: 回复：[ZLMediaKit/ZLToolKit] 安卓编译报错 (#68)





 
同步更新代码后，编译依然有报错，但错误信息不一样了。
 ZLToolKit/tests/test_threadPoolBenchmark.cpp: In lambda function: ZLToolKit/tests/test_threadPoolBenchmark.cpp:23:15: error: 'exit' was not declared in this scope          exit(0);                ^ At global scope: cc1plus: warning: unrecognized command line option "-Wno-predefined-identifier-outside-function" make[2]: *** [tests/CMakeFiles/test_threadPoolBenchmark.dir/test_threadPoolBenchmark.cpp.o] Error 1 make[1]: *** [tests/CMakeFiles/test_threadPoolBenchmark.dir/all] Error 2 make[1]: *** Waiting for unfinished jobs.... ../lib/libZLToolKit.a(logger.cpp.o):logger.cpp:function toolkit::ConsoleChannel::write(toolkit::Logger const&amp;, std::shared_ptr<toolkit::LogContext&gt; const&amp;): error: undefined reference to '__android_log_print' ../lib/libZLToolKit.a(logger.cpp.o):logger.cpp:function toolkit::ConsoleChannel::write(toolkit::Logger const&amp;, std::shared_ptr<toolkit::LogContext&gt; const&amp;): error: undefined reference to '__android_log_print' collect2: error: ld returned 1 exit status collect2: error: ld returned 1 exit status make[2]: *** [bin/test_udpSock] Error 1 make[2]: *** [bin/test_timer] Error 1 make[1]: *** [tests/CMakeFiles/test_udpSock.dir/all] Error 2 make[1]: *** [tests/CMakeFiles/test_timer.dir/all] Error 2 ../lib/libZLToolKit.a(logger.cpp.o):logger.cpp:function toolkit::ConsoleChannel::write(toolkit::Logger const&amp;, std::shared_ptr<toolkit::LogContext&gt; const&amp;): error: undefined reference to '__android_log_print' collect2: error: ld returned 1 exit status make[2]: *** [bin/test_tcpClient] Error 1 make[1]: *** [tests/CMakeFiles/test_tcpClient.dir/all] Error 2 make: *** [all] Error 2 ../lib/libZLToolKit.a(logger.cpp.o):logger.cpp:function toolkit::ConsoleChannel::write(toolkit::Logger const&amp;, std::shared_ptr<toolkit::LogContext&gt; const&amp;): error: undefined reference to '__android_log_print' collect2: error: ld returned 1 exit status make[2]: *** [bin/test_udpSock] Error 1 make[1]: *** [tests/CMakeFiles/test_udpSock.dir/all] Error 2 make: *** [all] Error 2
