### ISSUE TITLE
getCurrentMicrosecondOrigin 获取时间可能有随机的错误

### ISSUE THREAD

**Issue by bzd2132** [ZLMediaKit/ZLToolKit#76]
运行平台：Linux, ARMv7
现象：
运行过程中会打印下面的日志。

> 2021-11-24 14:45:35.000 W test[1279-stamp thread] util.cpp:362 operator() | Stamp expired is not abnormal:-6631
> 2021-11-24 14:46:49.000 W test[1279-stamp thread] util.cpp:362 operator() | Stamp expired is not abnormal:-319974
> 2021-11-24 14:47:26.000 W test[1279-stamp thread] util.cpp:362 operator() | Stamp expired is not abnormal:-233909
> 2021-11-24 14:48:03.000 W test[1279-stamp thread] util.cpp:362 operator() | Stamp expired is not abnormal:-137712
原因：
在util.cpp中的getCurrentMicrosecondOrigin函数，获取的时间有可能会出现小于前面的获取的情况。

```
static inline uint64_t getCurrentMicrosecondOrigin() {
#if !defined(_WIN32)
    struct timeval tv;
    gettimeofday(&tv, NULL);
    return tv.tv_sec * 1000000LL + tv.tv_usec;
#else
    return  std::chrono::duration_cast<std::chrono::microseconds>(std::chrono::system_clock::now().time_since_epoch()).count();
#endif
}
```
修改成下面的实现后，就不会出现了
```
static inline uint64_t getCurrentMicrosecondOrigin() {
#if !defined(_WIN32)
    struct timespec ts;
    clock_gettime(CLOCK_MONOTONIC, &ts);
    return ts.tv_sec * 1000000LL + ts.tv_nsec/1000;
#else
    return  std::chrono::duration_cast<std::chrono::microseconds>(std::chrono::system_clock::now().time_since_epoch()).count();
#endif
}
```
请帮忙看看修改是否有问题。谢谢！

**Comment by xia-chu** [comment]
其实Stamp expired is not abnormal:-6631这个打印不会影响程序正常的运行的， 代码有做系统时间戳回退的处理的。
我建议先都统一改用`return  std::chrono::duration_cast<std::chrono::microseconds>(std::chrono::system_clock::now().time_since_epoch()).count()`测试下 ，我觉得有c++11支持的了 就没必要用平台专属api了

**Comment by bzd2132** [comment]
感谢反馈，我有试过`std::chrono::duration_cast<std::chrono::microseconds>(std::chrono::system_clock::now().time_since_epoch()).count();` 也是会有同样的打印。如果不影响正常运行那就没事。
